### ISSUE TITLE
Crash?

### ISSUE THREAD

**Issue by marius00** [marius00/iagd#117]
2021-05-16 12:42:26,379 [BackupServiceWorker] DEBUG IAGrim.Backup.Cloud.Service.BackupService Storing batch of 100 items
Exception thrown: 'System.AggregateException' in mscorlib.dll
2021-05-16 12:42:26,417 [BuddyBackground] ERROR IAGrim.BuddyShare.BuddyItemsService One or more errors occurred.
2021-05-16 12:42:26,418 [BuddyBackground] ERROR IAGrim.BuddyShare.BuddyItemsService    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at IAGrim.Utilities.HelperClasses.RestService.Get[T](String url) in F:\Dev\IAGrim\IAGrim\Utilities\HelperClasses\RestService.cs:line 31
   at IAGrim.BuddyShare.BuddyItemsService.bw_DoWork(Object sender, DoWorkEventArgs e) in F:\Dev\IAGrim\IAGrim\BuddyShare\BuddyItemsService.cs:line 100
2021-05-16 12:42:26,635 [SQL] INFO  IAGrim.Database.Interfaces.IPlayerItemDao Stored 100 player items to database.
2021-05-16 12:42:26,635 [BackupServiceWorker] DEBUG IAGrim.Backup.Cloud.Service.BackupService Storing batch of 100 items
2021-05-16 12:42:26,962 [SQL] INFO  IAGrim.Database.Interfaces.IPlayerItemDao Stored 100 player items to database.
2021-05-16 12:42:26,962 [BackupServiceWorker] DEBUG IAGrim.Backup.Cloud.Service.BackupService Storing batch of 50 items
2021-05-16 12:42:26,980 [ItemStatCache] DEBUG IAGrim.Services.ItemStatCacheService Updated cache for 50 items
2021-05-16 12:42:26,981 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying stats to 50 items
2021-05-16 12:42:26,983 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying stats to 50 items
2021-05-16 12:42:27,168 [SQL] INFO  IAGrim.Database.Interfaces.IPlayerItemDao Stored 50 player items to database.
2021-05-16 12:42:27,194 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying skills to items
2021-05-16 12:42:27,209 [BackupServiceWorker] DEBUG IAGrim.Backup.Cloud.Service.BackupService Updated/Merged in 450 items, new timestamp is 1621161744
Exception thrown: 'System.InvalidOperationException' in System.Core.dll
2021-05-16 12:42:27,221 [BackupServiceWorker] ERROR IAGrim.Backup.Cloud.Util.BackupServiceWorker Sequence contains no elements
2021-05-16 12:42:27,231 [BackupServiceWorker] ERROR IAGrim.Backup.Cloud.Util.BackupServiceWorker    at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source)
   at IAGrim.Utilities.Cloud.FileBackup.GetHighestCharacterTimestamp() in F:\Dev\IAGrim\IAGrim\Utilities\Cloud\FileBackup.cs:line 149
   at IAGrim.Backup.Cloud.Service.CharacterBackupService.ExecuteInternal() in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Service\CharacterBackupService.cs:line 62
   at IAGrim.Utilities.ActionCooldown.ExecuteIfReady(Action a) in F:\Dev\IAGrim\IAGrim\Utilities\ActionCooldown.cs:line 26
   at IAGrim.Backup.Cloud.Service.CharacterBackupService.Execute() in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Service\CharacterBackupService.cs:line 42
   at IAGrim.Backup.Cloud.Util.BackupServiceWorker.bw_DoWork(Object sender, DoWorkEventArgs e) in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Util\BackupServiceWorker.cs:line 49
2021-05-16 12:42:27,238 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying stats to skills for 18 items
2021-05-16 12:42:27,246 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Skills applied
2021-05-16 12:42:27,250 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applied stats to 50 items
Exception thrown: 'System.InvalidOperationException' in System.Core.dll
2021-05-16 12:42:28,241 [BackupServiceWorker] ERROR IAGrim.Backup.Cloud.Util.BackupServiceWorker Sequence contains no elements
2021-05-16 12:42:28,241 [BackupServiceWorker] ERROR IAGrim.Backup.Cloud.Util.BackupServiceWorker    at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source)
   at IAGrim.Utilities.Cloud.FileBackup.GetHighestCharacterTimestamp() in F:\Dev\IAGrim\IAGrim\Utilities\Cloud\FileBackup.cs:line 149
   at IAGrim.Backup.Cloud.Service.CharacterBackupService.ExecuteInternal() in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Service\CharacterBackupService.cs:line 62
   at IAGrim.Utilities.ActionCooldown.ExecuteIfReady(Action a) in F:\Dev\IAGrim\IAGrim\Utilities\ActionCooldown.cs:line 26
   at IAGrim.Backup.Cloud.Service.CharacterBackupService.Execute() in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Service\CharacterBackupService.cs:line 42
   at IAGrim.Backup.Cloud.Util.BackupServiceWorker.bw_DoWork(Object sender, DoWorkEventArgs e) in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Util\BackupServiceWorker.cs:line 49
2021-05-16 12:42:28,878 [ItemStatCache] DEBUG IAGrim.Services.ItemStatCacheService Updated cache for 50 items
2021-05-16 12:42:28,878 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying stats to 50 items
2021-05-16 12:42:28,878 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying stats to 50 items
2021-05-16 12:42:28,913 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying skills to items
2021-05-16 12:42:28,928 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying stats to skills for 13 items
2021-05-16 12:42:28,944 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Skills applied
2021-05-16 12:42:28,945 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applied stats to 50 items
Exception thrown: 'System.InvalidOperationException' in System.Core.dll
2021-05-16 12:42:29,254 [BackupServiceWorker] ERROR IAGrim.Backup.Cloud.Util.BackupServiceWorker Sequence contains no elements
2021-05-16 12:42:29,254 [BackupServiceWorker] ERROR IAGrim.Backup.Cloud.Util.BackupServiceWorker    at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source)
   at IAGrim.Utilities.Cloud.FileBackup.GetHighestCharacterTimestamp() in F:\Dev\IAGrim\IAGrim\Utilities\Cloud\FileBackup.cs:line 149
   at IAGrim.Backup.Cloud.Service.CharacterBackupService.ExecuteInternal() in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Service\CharacterBackupService.cs:line 62
   at IAGrim.Utilities.ActionCooldown.ExecuteIfReady(Action a) in F:\Dev\IAGrim\IAGrim\Utilities\ActionCooldown.cs:line 26
   at IAGrim.Backup.Cloud.Service.CharacterBackupService.Execute() in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Service\CharacterBackupService.cs:line 42
   at IAGrim.Backup.Cloud.Util.BackupServiceWorker.bw_DoWork(Object sender, DoWorkEventArgs e) in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Util\BackupServiceWorker.cs:line 49
Exception thrown: 'System.InvalidOperationException' in System.Core.dll
2021-05-16 12:42:30,266 [BackupServiceWorker] ERROR IAGrim.Backup.Cloud.Util.BackupServiceWorker Sequence contains no elements
2021-05-16 12:42:30,266 [BackupServiceWorker] ERROR IAGrim.Backup.Cloud.Util.BackupServiceWorker    at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source)
   at IAGrim.Utilities.Cloud.FileBackup.GetHighestCharacterTimestamp() in F:\Dev\IAGrim\IAGrim\Utilities\Cloud\FileBackup.cs:line 149
   at IAGrim.Backup.Cloud.Service.CharacterBackupService.ExecuteInternal() in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Service\CharacterBackupService.cs:line 62
   at IAGrim.Utilities.ActionCooldown.ExecuteIfReady(Action a) in F:\Dev\IAGrim\IAGrim\Utilities\ActionCooldown.cs:line 26
   at IAGrim.Backup.Cloud.Service.CharacterBackupService.Execute() in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Service\CharacterBackupService.cs:line 42
   at IAGrim.Backup.Cloud.Util.BackupServiceWorker.bw_DoWork(Object sender, DoWorkEventArgs e) in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Util\BackupServiceWorker.cs:line 49
2021-05-16 12:42:30,544 [ItemStatCache] DEBUG IAGrim.Services.ItemStatCacheService Updated cache for 50 items
2021-05-16 12:42:30,544 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying stats to 50 items
2021-05-16 12:42:30,544 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying stats to 50 items
2021-05-16 12:42:30,572 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying skills to items
2021-05-16 12:42:30,593 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying stats to skills for 12 items
2021-05-16 12:42:30,605 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Skills applied
2021-05-16 12:42:30,607 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applied stats to 50 items
Exception thrown: 'System.InvalidOperationException' in System.Core.dll
2021-05-16 12:42:31,278 [BackupServiceWorker] ERROR IAGrim.Backup.Cloud.Util.BackupServiceWorker Sequence contains no elements
2021-05-16 12:42:31,278 [BackupServiceWorker] ERROR IAGrim.Backup.Cloud.Util.BackupServiceWorker    at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source)
   at IAGrim.Utilities.Cloud.FileBackup.GetHighestCharacterTimestamp() in F:\Dev\IAGrim\IAGrim\Utilities\Cloud\FileBackup.cs:line 149
   at IAGrim.Backup.Cloud.Service.CharacterBackupService.ExecuteInternal() in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Service\CharacterBackupService.cs:line 62
   at IAGrim.Utilities.ActionCooldown.ExecuteIfReady(Action a) in F:\Dev\IAGrim\IAGrim\Utilities\ActionCooldown.cs:line 26
   at IAGrim.Backup.Cloud.Service.CharacterBackupService.Execute() in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Service\CharacterBackupService.cs:line 42
   at IAGrim.Backup.Cloud.Util.BackupServiceWorker.bw_DoWork(Object sender, DoWorkEventArgs e) in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Util\BackupServiceWorker.cs:line 49
2021-05-16 12:42:31,523 [BuddyBackground] INFO  IAGrim.BuddyShare.BuddyItemsService Fetching own buddy ID from cloud
2021-05-16 12:42:32,211 [ItemStatCache] DEBUG IAGrim.Services.ItemStatCacheService Updated cache for 50 items
2021-05-16 12:42:32,211 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying stats to 50 items
2021-05-16 12:42:32,211 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying stats to 50 items
2021-05-16 12:42:32,242 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying skills to items
2021-05-16 12:42:32,259 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying stats to skills for 16 items
2021-05-16 12:42:32,272 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Skills applied
2021-05-16 12:42:32,273 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applied stats to 50 items
Exception thrown: 'System.InvalidOperationException' in System.Core.dll
2021-05-16 12:42:32,290 [BackupServiceWorker] ERROR IAGrim.Backup.Cloud.Util.BackupServiceWorker Sequence contains no elements
2021-05-16 12:42:32,290 [BackupServiceWorker] ERROR IAGrim.Backup.Cloud.Util.BackupServiceWorker    at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source)
   at IAGrim.Utilities.Cloud.FileBackup.GetHighestCharacterTimestamp() in F:\Dev\IAGrim\IAGrim\Utilities\Cloud\FileBackup.cs:line 149
   at IAGrim.Backup.Cloud.Service.CharacterBackupService.ExecuteInternal() in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Service\CharacterBackupService.cs:line 62
   at IAGrim.Utilities.ActionCooldown.ExecuteIfReady(Action a) in F:\Dev\IAGrim\IAGrim\Utilities\ActionCooldown.cs:line 26
   at IAGrim.Backup.Cloud.Service.CharacterBackupService.Execute() in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Service\CharacterBackupService.cs:line 42
   at IAGrim.Backup.Cloud.Util.BackupServiceWorker.bw_DoWork(Object sender, DoWorkEventArgs e) in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Util\BackupServiceWorker.cs:line 49
Exception thrown: 'System.InvalidOperationException' in System.Core.dll
2021-05-16 12:42:33,300 [BackupServiceWorker] ERROR IAGrim.Backup.Cloud.Util.BackupServiceWorker Sequence contains no elements
2021-05-16 12:42:33,301 [BackupServiceWorker] ERROR IAGrim.Backup.Cloud.Util.BackupServiceWorker    at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source)
   at IAGrim.Utilities.Cloud.FileBackup.GetHighestCharacterTimestamp() in F:\Dev\IAGrim\IAGrim\Utilities\Cloud\FileBackup.cs:line 149
   at IAGrim.Backup.Cloud.Service.CharacterBackupService.ExecuteInternal() in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Service\CharacterBackupService.cs:line 62
   at IAGrim.Utilities.ActionCooldown.ExecuteIfReady(Action a) in F:\Dev\IAGrim\IAGrim\Utilities\ActionCooldown.cs:line 26
   at IAGrim.Backup.Cloud.Service.CharacterBackupService.Execute() in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Service\CharacterBackupService.cs:line 42
   at IAGrim.Backup.Cloud.Util.BackupServiceWorker.bw_DoWork(Object sender, DoWorkEventArgs e) in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Util\BackupServiceWorker.cs:line 49
2021-05-16 12:42:33,873 [ItemStatCache] DEBUG IAGrim.Services.ItemStatCacheService Updated cache for 50 items
2021-05-16 12:42:33,873 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying stats to 50 items
2021-05-16 12:42:33,873 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying stats to 50 items
2021-05-16 12:42:33,900 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying skills to items
2021-05-16 12:42:33,908 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying stats to skills for 13 items
2021-05-16 12:42:33,921 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Skills applied
2021-05-16 12:42:33,925 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applied stats to 50 items
Exception thrown: 'System.InvalidOperationException' in System.Core.dll
2021-05-16 12:42:34,316 [BackupServiceWorker] ERROR IAGrim.Backup.Cloud.Util.BackupServiceWorker Sequence contains no elements
2021-05-16 12:42:34,317 [BackupServiceWorker] ERROR IAGrim.Backup.Cloud.Util.BackupServiceWorker    at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source)
   at IAGrim.Utilities.Cloud.FileBackup.GetHighestCharacterTimestamp() in F:\Dev\IAGrim\IAGrim\Utilities\Cloud\FileBackup.cs:line 149
   at IAGrim.Backup.Cloud.Service.CharacterBackupService.ExecuteInternal() in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Service\CharacterBackupService.cs:line 62
   at IAGrim.Utilities.ActionCooldown.ExecuteIfReady(Action a) in F:\Dev\IAGrim\IAGrim\Utilities\ActionCooldown.cs:line 26
   at IAGrim.Backup.Cloud.Service.CharacterBackupService.Execute() in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Service\CharacterBackupService.cs:line 42
   at IAGrim.Backup.Cloud.Util.BackupServiceWorker.bw_DoWork(Object sender, DoWorkEventArgs e) in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Util\BackupServiceWorker.cs:line 49
Exception thrown: 'System.InvalidOperationException' in System.Core.dll
2021-05-16 12:42:35,328 [BackupServiceWorker] ERROR IAGrim.Backup.Cloud.Util.BackupServiceWorker Sequence contains no elements
2021-05-16 12:42:35,328 [BackupServiceWorker] ERROR IAGrim.Backup.Cloud.Util.BackupServiceWorker    at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source)
   at IAGrim.Utilities.Cloud.FileBackup.GetHighestCharacterTimestamp() in F:\Dev\IAGrim\IAGrim\Utilities\Cloud\FileBackup.cs:line 149
   at IAGrim.Backup.Cloud.Service.CharacterBackupService.ExecuteInternal() in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Service\CharacterBackupService.cs:line 62
   at IAGrim.Utilities.ActionCooldown.ExecuteIfReady(Action a) in F:\Dev\IAGrim\IAGrim\Utilities\ActionCooldown.cs:line 26
   at IAGrim.Backup.Cloud.Service.CharacterBackupService.Execute() in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Service\CharacterBackupService.cs:line 42
   at IAGrim.Backup.Cloud.Util.BackupServiceWorker.bw_DoWork(Object sender, DoWorkEventArgs e) in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Util\BackupServiceWorker.cs:line 49
2021-05-16 12:42:35,529 [ItemStatCache] DEBUG IAGrim.Services.ItemStatCacheService Updated cache for 50 items
2021-05-16 12:42:35,530 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying stats to 50 items
2021-05-16 12:42:35,530 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying stats to 50 items
2021-05-16 12:42:35,557 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying skills to items
2021-05-16 12:42:35,578 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying stats to skills for 11 items
2021-05-16 12:42:35,592 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Skills applied
2021-05-16 12:42:35,593 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applied stats to 50 items
Exception thrown: 'System.InvalidOperationException' in System.Core.dll
2021-05-16 12:42:36,342 [BackupServiceWorker] ERROR IAGrim.Backup.Cloud.Util.BackupServiceWorker Sequence contains no elements
2021-05-16 12:42:36,342 [BackupServiceWorker] ERROR IAGrim.Backup.Cloud.Util.BackupServiceWorker    at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source)
   at IAGrim.Utilities.Cloud.FileBackup.GetHighestCharacterTimestamp() in F:\Dev\IAGrim\IAGrim\Utilities\Cloud\FileBackup.cs:line 149
   at IAGrim.Backup.Cloud.Service.CharacterBackupService.ExecuteInternal() in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Service\CharacterBackupService.cs:line 62
   at IAGrim.Utilities.ActionCooldown.ExecuteIfReady(Action a) in F:\Dev\IAGrim\IAGrim\Utilities\ActionCooldown.cs:line 26
   at IAGrim.Backup.Cloud.Service.CharacterBackupService.Execute() in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Service\CharacterBackupService.cs:line 42
   at IAGrim.Backup.Cloud.Util.BackupServiceWorker.bw_DoWork(Object sender, DoWorkEventArgs e) in F:\Dev\IAGrim\IAGrim\Backup\Cloud\Util\BackupServiceWorker.cs:line 49
2021-05-16 12:42:37,182 [ItemStatCache] DEBUG IAGrim.Services.ItemStatCacheService Updated cache for 50 items
2021-05-16 12:42:37,182 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying stats to 50 items
2021-05-16 12:42:37,182 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying stats to 50 items
2021-05-16 12:42:37,209 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying skills to items
2021-05-16 12:42:37,235 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applying stats to skills for 8 items
2021-05-16 12:42:37,244 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Skills applied
2021-05-16 12:42:37,245 [ItemStatCache] DEBUG IAGrim.Services.ItemStatService Applied stats to 50 items

**Comment by marius00** [comment]
Possibly related to using methods from the newer Net framework, where MoreLinq was used previously. Or an issue that only presents itself when no characters exists.

Either way a fix has been pushed.
