### ISSUE TITLE
Does not automatically open the "try running as admin" help tab

### ISSUE THREAD

**Issue by marius00** [marius00/iagd#202]
A user was running GD + Steam as administrator and IA without, IA did not auto-detect the issue:

2023-11-21 10:05:22,793 [Main] DEBUG[IAGrim.GrimDawnDetector]: Looking for Grim Dawn GOG install..
2023-11-21 10:05:22,793 [Main] DEBUG[IAGrim.GrimDawnDetector]: Grim Dawn GOG install not found..
2023-11-21 10:05:22,815 [Main] WARN [IAGrim.GrimDawnDetector]: Access is denied
2023-11-21 10:05:22,815 [Main] WARN [IAGrim.GrimDawnDetector]:    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.OpenProcessHandle(Int32 access)
   at System.Diagnostics.Process.get_Handle()
   at EvilsoftCommons.DllInjector.DllInjector.Is64BitProcess(Process process)
   at IAGrim.GrimDawnDetector.GetProcessPath(UInt32 pid)
2023-11-21 10:05:22,815 [Main] FATAL[IAGrim.GrimDawnDetector]: ACCESS_DENIED obtaining the Grim Dawn process -- IA will run in limited usability mode, and will not function for GoG installs.
2023-11-21 10:05:22,815 [Main] INFO [IAGrim.GrimDawnDetector]: Running IA as administrator may solve this issue.
2023-11-21 10:05:22,990 [Main] WARN [IAGrim.GrimDawnDetector]: Object reference not set to an instance of an object.
2023-11-21 10:05:22,990 [Main] WARN [IAGrim.GrimDawnDetector]:    at IAGrim.GrimDawnDetector.FindViaManagmentSearch()

**Comment by marius00** [comment]
Should already be implemented via INJECTION_ERROR_POSSIBLE_ACCESS_DENIED... 🤔

**Comment by marius00** [comment]
Probably a user error.. seems to work fine locally.
