### ISSUE TITLE
Google drive support is broken

### ISSUE THREAD

**Issue by marius00** [marius00/iagd#25]
Multiple reports received about the google drive checkbox not working anymore.

A user has posted a possible explanation on the forum
http://www.grimdawn.com/forums/showpost.php?p=646528&postcount=1765

Currently not a prioritized issue, all users are recommended to use the cloud backup solution.

**Comment by marius00** [comment]
**From a user report:**

2018-06-30 22:56:14,738 [Main] WARN [EvilsoftCommons.Cloud.CloudWatcher]: No current row
2018-06-30 22:56:14,738 [Main] WARN [EvilsoftCommons.Cloud.CloudWatcher]:    at System.Data.SQLite.SQLiteDataReader.CheckValidRow()
   at System.Data.SQLite.SQLiteDataReader.GetValue(Int32 i)
   at System.Data.SQLite.SQLiteDataReader.get_Item(String name)
   at EvilsoftCommons.Cloud.CloudWatcher.FindGoogleDrive()

**Comment by Eradev** [comment]
Google Drive was discontinued over a year ago. I couldn't even run the old version saying it's outdated.

I think it's safe to close this issue.
