### ISSUE TITLE
IA throwing a fit ("crash")

### ISSUE THREAD

**Issue by marius00** [marius00/iagd#26]
Every time IA is updated, it tries to parse item stats and I'm getting this ltitle gem:

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at IAGrim.UI.UpdatingPlayerItemsScreen.bw_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)

**Comment by marius00** [comment]
Fixed, included in the cefsharp update.
