### ISSUE TITLE
Exceptions While Trying To Restore Export

### ISSUE THREAD

**Issue by mattimus-run** [marius00/iagd#97]
Exported on one computer and restored on another, previously this was never an issue but recently I started getting the following when trying to restore an import.

************** Exception Text **************
System.IO.InvalidDataException: This format of IAStash files is not supported, expected 1,2,3, got 4
   at IAGrim.Backup.FileWriter.IAFileExporter.Read(Byte[] bytes)
   at IAGrim.UI.Popups.ImportExport.Panels.ImportMode.buttonImport_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Tried updating to the most recent release and now get the following error:

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at EvilsoftCommons.IOHelper.GetBytePrefixedString(Byte[] data, Int32 pos)
   at IAGrim.Backup.FileWriter.IAFileExporter.<Read>g__ReadString|4_0(<>c__DisplayClass4_0& )
   at IAGrim.Backup.FileWriter.IAFileExporter.Read(Byte[] bytes)
   at IAGrim.UI.Popups.ImportExport.Panels.ImportMode.buttonImport_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Probably user error but just passing it along, not sure what upgrade/downgrade scenarios are supported.

Thank you for the addon, greatly appreciated.

**Comment by marius00** [comment]
Fixed in v1.2.7629.13533

**Comment by marius00** [comment]
If you enable experimental updates and restart IA, you should get an update notification.
